In [1]:
import pandas as pd
import numpy as np

In [2]:
url = 'data_infonieve.csv'
df = pd.read_csv(url)

In [3]:
df.head(16)

,id,name,downhill_skiing,nordic_skiing,opening_date,opening_confirmed,closing_date,snowreports,date,updated,...,avalanche_risk,avalanche_risk_text,comment,extended_elements,snowpark,special_runs_text,special_runs_open,special_runs_total,trineos,esqui_de_fondo
0,22001,Alp 2500,1,0,02/12/2022,1,10/04/2023,"{'date': '2023-01-20', 'updated': '2023-01-20 ...",2023-01-20,2023-01-20 11:24:09,...,0,Sin Riesgo,Apertura parcial debida a condiciones meteorol...,"[{'group_name': 'Dominio', 'group_items': [{'e...",0,NaN,NaN,NaN,NaN,NaN
1,20,La Molina,1,0,03/12/2022,1,10/04/2023,"{'date': '2023-01-20', 'updated': '2023-01-20 ...",2023-01-20,2023-01-20 11:24:09,...,0,Sin Riesgo,Apertura parcial debida a condiciones meteorol...,"[{'group_name': 'Actividades', 'group_items': ...",1,NaN,NaN,NaN,NaN,NaN
2,19,Masella,1,0,02/12/2022,1,10/04/2023,"{'date': '2023-01-20', 'updated': '2023-01-20 ...",2023-01-20,2023-01-20 11:24:09,...,-1,sin información,Apertura parcial debida a condiciones meteorol...,"[{'group_name': 'Dominio', 'group_items': [{'e...",0,NaN,NaN,NaN,NaN,NaN
3,16,Baqueira Beret,1,0,26/11/2022,1,10/04/2023,"{'date': '2023-01-20', 'updated': '2023-01-20 ...",2023-01-20,2023-01-20 11:24:09,...,4,Fuerte,Previsión de condiciones meteorológicas advers...,"[{'group_name': 'Actividades', 'group_items': ...",1,Itinerarios,-,3.0,NaN,NaN
4,17,Boí Taüll,1,0,02/12/2022,1,10/04/2023,"{'date': '2023-01-20', 'updated': '2023-01-20 ...",2023-01-20,2023-01-20 13:04:44,...,3,Notable,Apertura parcial debida a condiciones meteorol...,"[{'group_name': 'Actividades', 'group_items': ...",1,NaN,NaN,NaN,NaN,NaN
5,18,Espot,1,0,02/12/2022,1,31/03/2023,"{'date': '2023-01-20', 'updated': '2023-01-20 ...",2023-01-20,2023-01-20 08:49:02,...,4,Fuerte,Apertura parcial debida a condiciones meteorol...,"[{'group_name': 'Actividades', 'group_items': ...",0,NaN,NaN,NaN,NaN,NaN
6,21,Port Ainé,1,0,02/12/2022,1,10/04/2023,"{'date': '2023-01-20', 'updated': '2023-01-20 ...",2023-01-20,2023-01-20 11:24:09,...,2,Limitado,Apertura parcial debida a condiciones meteorol...,"[{'group_name': 'Actividades', 'group_items': ...",1,NaN,NaN,NaN,NaN,NaN
7,22,Port del Comte,1,0,03/12/2022,1,10/03/2023,"{'date': '2023-01-20', 'updated': '2023-01-20 ...",2023-01-20,2023-01-20 08:49:02,...,-1,sin información,Previsión de condiciones meteorológicas advers...,"[{'group_name': 'Sectores', 'group_items': [{'...",0,NaN,NaN,NaN,NaN,NaN
8,2412,Tavascán,1,0,07/12/2022,1,09/04/2023,"{'date': '2023-01-20', 'updated': '2023-01-20 ...",2023-01-20,2023-01-20 09:27:56,...,3,Notable,Estación cerrada hoy debido a condiciones mete...,NaN,0,NaN,NaN,NaN,NaN,NaN
9,23,Vall de Nuria,1,0,03/12/2022,1,09/04/2023,"{'date': '2023-01-20', 'updated': '2023-01-20 ...",2023-01-20,2023-01-20 08:49:02,...,0,Sin Riesgo,Apertura parcial debida a condiciones meteorol...,"[{'group_name': 'Actividades', 'group_items': ...",0,NaN,NaN,NaN,NaN,NaN
10,24,Vallter,1,0,04/12/2022,1,22/03/2023,"{'date': '2023-01-20', 'updated': '2023-01-20 ...",2023-01-20,2023-01-20 08:49:02,...,0,Sin Riesgo,Estación cerrada hoy debido a condiciones mete...,"[{'group_name': 'Actividades', 'group_items': ...",0,NaN,NaN,NaN,NaN,NaN
11,22003,100K Astún - Candanchú,1,0,03/12/2022,1,09/04/2023,"{'date': '2023-01-20', 'updated': '2023-01-20 ...",2023-01-20,2023-01-20 08:49:02,...,3,Notable,Previsión de condiciones meteorológicas advers...,NaN,0,Itinerarios,-,10.0,NaN,NaN
12,7,Astún,1,0,03/12/2022,1,09/04/2023,"{'date': '2023-01-20', 'updated': '2023-01-20 ...",2023-01-20,2023-01-20 08:49:02,...,3,Notable,Previsión de condiciones meteorológicas advers...,"[{'group_name': 'Actividades', 'group_items': ...",1,Itinerarios,-,10.0,NaN,NaN
13,8,Candanchú,1,0,03/12/2022,1,09/04/2023,"{'date': '2023-01-20', 'updated': '2023-01-20 ...",2023-01-20,2023-01-20 08:49:02,...,3,Notable,Previsión de condiciones meteorológicas advers...,"[{'group_name': 'Actividades', 'group_items': ...",0,NaN,NaN,NaN,NaN,NaN
14,9,Cerler,1,0,06/12/2022,1,09/04/2023,"{'date': '2023-01-20', 'updated': '2023-01-20 ...",2023-01-20,2023-01-20 08:49:02,...,-1,sin información,Estación cerrada hoy debido a condiciones mete...,"[{'group_name': 'Actividades', 'group_items': ...",1,Itinerarios,-,1.0,NaN,NaN
15,22002,Formigal - Panticosa,1,0,03/12/2022,1,09/04/2023,"{'date': '2023-01-20', 'updated': '2023-01-20 ...",2023-01-20,2023-01-20 11:24:09,...,3,Notable,Previsión de condiciones meteorológicas advers...,NaN,0,Itinerarios,-,5.0,NaN,NaN

In [4]:
df.isna().sum()

id                      0
name                    0
downhill_skiing         0
nordic_skiing           0
opening_date            0
opening_confirmed       0
closing_date            0
snowreports             0
date                    0
updated                 0
status_id               0
status_open             0
status_text             0
lifts_open              0
lifts_total             0
runs_open               0
runs_total              0
km_open                 0
km_total                0
snowdepth_min           0
snowdepth_max           0
snow_quality            0
green_runs_open         0
green_runs_total        0
blue_runs_open          0
blue_runs_total         0
red_runs_open           0
red_runs_total          0
black_runs_open         0
black_runs_total        0
special_runs            0
avalanche_risk          0
avalanche_risk_text     0
comment                23
extended_elements      17
snowpark                0
special_runs_text      57
special_runs_open      57
special_runs_total     57
trineos                16
esqui_de_fondo         16
dtype: int64

In [5]:
df.trineos.loc[0] = 0
df.esqui_de_fondo.loc[0] = 0

df.trineos.loc[1] = 1
df.esqui_de_fondo.loc[1] = 0

df.trineos.loc[2] = 0
df.esqui_de_fondo.loc[2] = 0

df.trineos.loc[3] = 0
df.esqui_de_fondo.loc[3] = 1

df.trineos.loc[4] = 1
df.esqui_de_fondo.loc[4] = 0

df.trineos.loc[5] = 1
df.esqui_de_fondo.loc[5] = 0

df.trineos.loc[6] = 1
df.esqui_de_fondo.loc[6] = 0

df.trineos.loc[7] = 0
df.esqui_de_fondo.loc[7] = 0

df.trineos.loc[8] = 0
df.esqui_de_fondo.loc[8] = 0

df.trineos.loc[9] = 1
df.esqui_de_fondo.loc[9] = 0

df.trineos.loc[10] = 1
df.esqui_de_fondo.loc[10] = 0

df.trineos.loc[11] = 0
df.esqui_de_fondo.loc[11] = 0

df.trineos.loc[12] = 1
df.esqui_de_fondo.loc[12] = 0

df.trineos.loc[13] = 1
df.esqui_de_fondo.loc[13] = 0

df.trineos.loc[14] = 0
df.esqui_de_fondo.loc[14] = 0

df.trineos.loc[15] = 0
df.esqui_de_fondo.loc[15] = 0

df.trineos.loc[16] = 0
df.esqui_de_fondo.loc[16] = 0

C:\Users\v1cto\AppData\Local\Temp\ipykernel_5060\1364333067.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.trineos.loc[0] = 0
C:\Users\v1cto\AppData\Local\Temp\ipykernel_5060\1364333067.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.esqui_de_fondo.loc[0] = 0
C:\Users\v1cto\AppData\Local\Temp\ipykernel_5060\1364333067.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.trineos.loc[1] = 1
C:\Users\v1cto\AppData\Local\Temp\ipykernel_5060\1364333067.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.esqui_de_fondo.loc[1] = 0
C:\Users\v1cto\AppData\Local\Temp\ipykernel_5060\1364333067.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.trineos.loc[2] = 0
C:\Users\v1cto\AppData\Local\Temp\ipykernel_5060\1364333067.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.esqui_de_fondo.loc[2] = 0
C:\Users\v1cto\AppData\Local\Temp\ipykernel_5060\1364333067.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.trineos.loc[3] = 0
C:\Users\v1cto\AppData\Local\Temp\ipykernel_5060\1364333067.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.esqui_de_fondo.loc[3] = 1
C:\Users\v1cto\AppData\Local\Temp\ipykernel_5060\1364333067.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.trineos.loc[4] = 1
C:\Users\v1cto\AppData\Local\Temp\ipykernel_5060\1364333067.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.esqui_de_fondo.loc[4] = 0
C:\Users\v1cto\AppData\Local\Temp\ipykernel_5060\1364333067.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.trineos.loc[5] = 1
C:\Users\v1cto\AppData\Local\Temp\ipykernel_5060\1364333067.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.esqui_de_fondo.loc[5] = 0
C:\Users\v1cto\AppData\Local\Temp\ipykernel_5060\1364333067.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.trineos.loc[6] = 1
C:\Users\v1cto\AppData\Local\Temp\ipykernel_5060\1364333067.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.esqui_de_fondo.loc[6] = 0
C:\Users\v1cto\AppData\Local\Temp\ipykernel_5060\1364333067.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.trineos.loc[7] = 0
C:\Users\v1cto\AppData\Local\Temp\ipykernel_5060\1364333067.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.esqui_de_fondo.loc[7] = 0
C:\Users\v1cto\AppData\Local\Temp\ipykernel_5060\1364333067.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.trineos.loc[8] = 0
C:\Users\v1cto\AppData\Local\Temp\ipykernel_5060\1364333067.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.esqui_de_fondo.loc[8] = 0
C:\Users\v1cto\AppData\Local\Temp\ipykernel_5060\1364333067.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.trineos.loc[9] = 1
C:\Users\v1cto\AppData\Local\Temp\ipykernel_5060\1364333067.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.esqui_de_fondo.loc[9] = 0
C:\Users\v1cto\AppData\Local\Temp\ipykernel_5060\1364333067.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.trineos.loc[10] = 1
C:\Users\v1cto\AppData\Local\Temp\ipykernel_5060\1364333067.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.esqui_de_fondo.loc[10] = 0
C:\Users\v1cto\AppData\Local\Temp\ipykernel_5060\1364333067.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.trineos.loc[11] = 0
C:\Users\v1cto\AppData\Local\Temp\ipykernel_5060\1364333067.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.esqui_de_fondo.loc[11] = 0
C:\Users\v1cto\AppData\Local\Temp\ipykernel_5060\1364333067.py:37: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.trineos.loc[12] = 1
C:\Users\v1cto\AppData\Local\Temp\ipykernel_5060\1364333067.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.esqui_de_fondo.loc[12] = 0
C:\Users\v1cto\AppData\Local\Temp\ipykernel_5060\1364333067.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.trineos.loc[13] = 1
C:\Users\v1cto\AppData\Local\Temp\ipykernel_5060\1364333067.py:41: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.esqui_de_fondo.loc[13] = 0
C:\Users\v1cto\AppData\Local\Temp\ipykernel_5060\1364333067.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.trineos.loc[14] = 0
C:\Users\v1cto\AppData\Local\Temp\ipykernel_5060\1364333067.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.esqui_de_fondo.loc[14] = 0
C:\Users\v1cto\AppData\Local\Temp\ipykernel_5060\1364333067.py:46: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.trineos.loc[15] = 0
C:\Users\v1cto\AppData\Local\Temp\ipykernel_5060\1364333067.py:47: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.esqui_de_fondo.loc[15] = 0
C:\Users\v1cto\AppData\Local\Temp\ipykernel_5060\1364333067.py:49: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.trineos.loc[16] = 0
C:\Users\v1cto\AppData\Local\Temp\ipykernel_5060\1364333067.py:50: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.esqui_de_fondo.loc[16] = 0

In [6]:
df.isna().sum()

id                      0
name                    0
downhill_skiing         0
nordic_skiing           0
opening_date            0
opening_confirmed       0
closing_date            0
snowreports             0
date                    0
updated                 0
status_id               0
status_open             0
status_text             0
lifts_open              0
lifts_total             0
runs_open               0
runs_total              0
km_open                 0
km_total                0
snowdepth_min           0
snowdepth_max           0
snow_quality            0
green_runs_open         0
green_runs_total        0
blue_runs_open          0
blue_runs_total         0
red_runs_open           0
red_runs_total          0
black_runs_open         0
black_runs_total        0
special_runs            0
avalanche_risk          0
avalanche_risk_text     0
comment                23
extended_elements      17
snowpark                0
special_runs_text      57
special_runs_open      57
special_runs_total     57
trineos                 0
esqui_de_fondo          0
dtype: int64

In [7]:
df.dropna(axis=1)

,id,name,downhill_skiing,nordic_skiing,opening_date,opening_confirmed,closing_date,snowreports,date,updated,...,red_runs_open,red_runs_total,black_runs_open,black_runs_total,special_runs,avalanche_risk,avalanche_risk_text,snowpark,trineos,esqui_de_fondo
0,22001,Alp 2500,1,0,02/12/2022,1,10/04/2023,"{'date': '2023-01-20', 'updated': '2023-01-20 ...",2023-01-20,2023-01-20 11:24:09,...,5,44,-,16,0,0,Sin Riesgo,0,0.0,0.0
1,20,La Molina,1,0,03/12/2022,1,10/04/2023,"{'date': '2023-01-20', 'updated': '2023-01-20 ...",2023-01-20,2023-01-20 11:24:09,...,-,22,-,6,0,0,Sin Riesgo,1,1.0,0.0
2,19,Masella,1,0,02/12/2022,1,10/04/2023,"{'date': '2023-01-20', 'updated': '2023-01-20 ...",2023-01-20,2023-01-20 11:24:09,...,5,22,-,10,0,-1,sin información,0,0.0,0.0
3,16,Baqueira Beret,1,0,26/11/2022,1,10/04/2023,"{'date': '2023-01-20', 'updated': '2023-01-20 ...",2023-01-20,2023-01-20 11:24:09,...,20,48,3,17,1,4,Fuerte,1,0.0,1.0
4,17,Boí Taüll,1,0,02/12/2022,1,10/04/2023,"{'date': '2023-01-20', 'updated': '2023-01-20 ...",2023-01-20,2023-01-20 13:04:44,...,1,15,-,16,0,3,Notable,1,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63,1527,Formiguères,1,0,08/12/2022,1,09/03/2023,"[{'date': '2023-01-20', 'updated': '2023-01-20...",2023-01-20,2023-01-20 11:36:29,...,-,9,-,2,0,-1,sin información,0,0.0,0.0
64,1529,La Quillane,1,0,03/12/2022,1,12/03/2023,"[{'date': '2023-01-20', 'updated': '2023-01-20...",2023-01-20,2023-01-20 09:08:42,...,-,-,-,-,0,-1,sin información,0,0.0,0.0
65,237,Les Angles,1,0,03/12/2022,1,26/03/2023,"[{'date': '2023-01-20', 'updated': '2023-01-20...",2023-01-20,2023-01-20 11:36:29,...,-,14,-,8,0,4,Fuerte,1,1.0,1.0
66,1530,Porté-Puymorens,1,0,03/12/2022,1,26/03/2023,"[{'date': '2023-01-20', 'updated': '2023-01-20...",2023-01-20,2023-01-20 11:36:29,...,-,7,-,8,0,-1,sin información,0,0.0,0.0
67,1332,Serra da Estrela,1,0,05/01/2023,1,23/03/2023,"[{'date': '2023-01-20', 'updated': '2023-01-20...",2023-01-20,2023-01-20 10:21:19,...,-,11,-,1,0,-1,sin información,1,0.0,0.0

In [8]:
df.head(17)

,id,name,downhill_skiing,nordic_skiing,opening_date,opening_confirmed,closing_date,snowreports,date,updated,...,avalanche_risk,avalanche_risk_text,comment,extended_elements,snowpark,special_runs_text,special_runs_open,special_runs_total,trineos,esqui_de_fondo
0,22001,Alp 2500,1,0,02/12/2022,1,10/04/2023,"{'date': '2023-01-20', 'updated': '2023-01-20 ...",2023-01-20,2023-01-20 11:24:09,...,0,Sin Riesgo,Apertura parcial debida a condiciones meteorol...,"[{'group_name': 'Dominio', 'group_items': [{'e...",0,NaN,NaN,NaN,0.0,0.0
1,20,La Molina,1,0,03/12/2022,1,10/04/2023,"{'date': '2023-01-20', 'updated': '2023-01-20 ...",2023-01-20,2023-01-20 11:24:09,...,0,Sin Riesgo,Apertura parcial debida a condiciones meteorol...,"[{'group_name': 'Actividades', 'group_items': ...",1,NaN,NaN,NaN,1.0,0.0
2,19,Masella,1,0,02/12/2022,1,10/04/2023,"{'date': '2023-01-20', 'updated': '2023-01-20 ...",2023-01-20,2023-01-20 11:24:09,...,-1,sin información,Apertura parcial debida a condiciones meteorol...,"[{'group_name': 'Dominio', 'group_items': [{'e...",0,NaN,NaN,NaN,0.0,0.0
3,16,Baqueira Beret,1,0,26/11/2022,1,10/04/2023,"{'date': '2023-01-20', 'updated': '2023-01-20 ...",2023-01-20,2023-01-20 11:24:09,...,4,Fuerte,Previsión de condiciones meteorológicas advers...,"[{'group_name': 'Actividades', 'group_items': ...",1,Itinerarios,-,3.0,0.0,1.0
4,17,Boí Taüll,1,0,02/12/2022,1,10/04/2023,"{'date': '2023-01-20', 'updated': '2023-01-20 ...",2023-01-20,2023-01-20 13:04:44,...,3,Notable,Apertura parcial debida a condiciones meteorol...,"[{'group_name': 'Actividades', 'group_items': ...",1,NaN,NaN,NaN,1.0,0.0
5,18,Espot,1,0,02/12/2022,1,31/03/2023,"{'date': '2023-01-20', 'updated': '2023-01-20 ...",2023-01-20,2023-01-20 08:49:02,...,4,Fuerte,Apertura parcial debida a condiciones meteorol...,"[{'group_name': 'Actividades', 'group_items': ...",0,NaN,NaN,NaN,1.0,0.0
6,21,Port Ainé,1,0,02/12/2022,1,10/04/2023,"{'date': '2023-01-20', 'updated': '2023-01-20 ...",2023-01-20,2023-01-20 11:24:09,...,2,Limitado,Apertura parcial debida a condiciones meteorol...,"[{'group_name': 'Actividades', 'group_items': ...",1,NaN,NaN,NaN,1.0,0.0
7,22,Port del Comte,1,0,03/12/2022,1,10/03/2023,"{'date': '2023-01-20', 'updated': '2023-01-20 ...",2023-01-20,2023-01-20 08:49:02,...,-1,sin información,Previsión de condiciones meteorológicas advers...,"[{'group_name': 'Sectores', 'group_items': [{'...",0,NaN,NaN,NaN,0.0,0.0
8,2412,Tavascán,1,0,07/12/2022,1,09/04/2023,"{'date': '2023-01-20', 'updated': '2023-01-20 ...",2023-01-20,2023-01-20 09:27:56,...,3,Notable,Estación cerrada hoy debido a condiciones mete...,NaN,0,NaN,NaN,NaN,0.0,0.0
9,23,Vall de Nuria,1,0,03/12/2022,1,09/04/2023,"{'date': '2023-01-20', 'updated': '2023-01-20 ...",2023-01-20,2023-01-20 08:49:02,...,0,Sin Riesgo,Apertura parcial debida a condiciones meteorol...,"[{'group_name': 'Actividades', 'group_items': ...",0,NaN,NaN,NaN,1.0,0.0
10,24,Vallter,1,0,04/12/2022,1,22/03/2023,"{'date': '2023-01-20', 'updated': '2023-01-20 ...",2023-01-20,2023-01-20 08:49:02,...,0,Sin Riesgo,Estación cerrada hoy debido a condiciones mete...,"[{'group_name': 'Actividades', 'group_items': ...",0,NaN,NaN,NaN,1.0,0.0
11,22003,100K Astún - Candanchú,1,0,03/12/2022,1,09/04/2023,"{'date': '2023-01-20', 'updated': '2023-01-20 ...",2023-01-20,2023-01-20 08:49:02,...,3,Notable,Previsión de condiciones meteorológicas advers...,NaN,0,Itinerarios,-,10.0,0.0,0.0
12,7,Astún,1,0,03/12/2022,1,09/04/2023,"{'date': '2023-01-20', 'updated': '2023-01-20 ...",2023-01-20,2023-01-20 08:49:02,...,3,Notable,Previsión de condiciones meteorológicas advers...,"[{'group_name': 'Actividades', 'group_items': ...",1,Itinerarios,-,10.0,1.0,0.0
13,8,Candanchú,1,0,03/12/2022,1,09/04/2023,"{'date': '2023-01-20', 'updated': '2023-01-20 ...",2023-01-20,2023-01-20 08:49:02,...,3,Notable,Previsión de condiciones meteorológicas advers...,"[{'group_name': 'Actividades', 'group_items': ...",0,NaN,NaN,NaN,1.0,0.0
14,9,Cerler,1,0,06/12/2022,1,09/04/2023,"{'date': '2023-01-20', 'updated': '2023-01-20 ...",2023-01-20,2023-01-20 08:49:02,...,-1,sin información,Estación cerrada hoy debido a condiciones mete...,"[{'group_name': 'Actividades', 'group_items': ...",1,Itinerarios,-,1.0,0.0,0.0
15,22002,Formigal - Panticosa,1,0,03/12/2022,1,09/04/2023,"{'date': '2023-01-20', 'updated': '2023-01-20 ...",2023-01-20,2023-01-20 11:24:09,...,3,Notable,Previsión de condiciones meteorológicas advers...,NaN,0,Itinerarios,-,5.0,0.0,0.0
16,10,Formigal,1,0,03/12/2022,1,09/04/2023,"[{'date': '2023-01-20', 'updated': '2023-01-20...",2023-01-20,2023-01-20 11:24:09,...,3,Notable,Previsión de condiciones meteorológicas advers...,"[{'group_name': 'Actividades', 'group_items': ...",1,Itinerarios,-,4.0,0.0,0.0

In [9]:
df.trineos = df.trineos.astype(int)

df.esqui_de_fondo = df.esqui_de_fondo.astype(int)

In [10]:
df = df.drop(['avalanche_risk_text', 'avalanche_risk', 'comment', 'extended_elements', 'special_runs_text',
             'opening_date', 'opening_confirmed', 'closing_date', 'snowreports', 'date', 'status_open', 'status_text',
             'lifts_open', 'runs_open', 'km_open', 'snowdepth_min', 'snowdepth_max', 'snow_quality', 'green_runs_open',
              'blue_runs_open', 'red_runs_open', 'black_runs_open', 'special_runs_open'], axis=1)

In [11]:
df.columns

Index(['id', 'name', 'downhill_skiing', 'nordic_skiing', 'updated',
       'status_id', 'lifts_total', 'runs_total', 'km_total',
       'green_runs_total', 'blue_runs_total', 'red_runs_total',
       'black_runs_total', 'special_runs', 'snowpark', 'special_runs_total',
       'trineos', 'esqui_de_fondo'],
      dtype='object')

In [17]:
df = df.drop(['updated'], axis=1)

In [24]:
df.head(40)

,id,name,downhill_skiing,nordic_skiing,status_id,lifts_total,runs_total,km_total,green_runs_total,blue_runs_total,red_runs_total,black_runs_total,special_runs,snowpark,special_runs_total,trineos,esqui_de_fondo
0,22001,Alp 2500,1,0,1,33,138,145,29,49,44,16,0,0,NaN,0,0
1,20,La Molina,1,0,1,16,66,71,20,18,22,6,0,1,NaN,1,0
2,19,Masella,1,0,1,17,72,74,9,31,22,10,0,0,NaN,0,0
3,16,Baqueira Beret,1,0,1,36,116,170,5,43,48,17,1,1,3.0,0,1
4,17,Boí Taüll,1,0,1,10,43,46,6,6,15,16,0,1,NaN,1,0
5,18,Espot,1,0,1,5,22,25,2,10,6,4,0,0,NaN,1,0
6,21,Port Ainé,1,0,1,7,25,27,6,4,11,4,0,1,NaN,1,0
7,22,Port del Comte,1,0,1,17,39,50,8,13,12,6,0,0,NaN,0,0
8,2412,Tavascán,1,0,4,3,7,7,2,1,2,2,0,0,NaN,0,0
9,23,Vall de Nuria,1,0,1,7,11,8,3,3,3,2,0,0,NaN,1,0
10,24,Vallter,1,0,4,10,13,13,3,4,6,-,0,0,NaN,1,0
11,22003,100K Astún - Candanchú,1,0,1,37,118,"100,5",17,32,40,19,1,0,10.0,0,0
12,7,Astún,1,0,1,15,61,50,5,18,22,6,1,1,10.0,1,0
13,8,Candanchú,1,0,1,22,57,"50,5",12,14,18,13,0,0,NaN,1,0
14,9,Cerler,1,0,4,20,72,80,10,19,27,16,1,1,1.0,0,0
15,22002,Formigal - Panticosa,1,0,1,37,147,182,12,36,52,42,1,0,5.0,0,0
16,10,Formigal,1,0,1,22,102,143,6,20,35,37,1,1,4.0,0,0
17,11,Panticosa,1,0,1,15,45,39,6,16,17,5,1,0,1.0,0,0
18,15,Alto Campoo,1,0,1,12,23,"30,38",4,10,9,-,0,1,NaN,0,0
19,5448,Fuentes de Invierno,1,0,2,5,15,"8,76",3,3,6,3,0,0,NaN,0,0
20,25,Manzaneda,1,0,2,6,23,"16,75",1,13,8,1,0,0,NaN,0,0
21,14,San Isidro,1,0,6,15,32,"31,1",6,8,13,4,1,1,1.0,0,1
22,13,Valgrande-Pajares,1,0,6,7,38,"22,58",8,12,15,3,0,1,NaN,0,1
23,955,Valle Laciana - Leitariegos,1,0,2,8,14,"8,4",4,4,6,-,0,1,NaN,0,0
24,4685,Javalambre,1,0,6,9,18,15,5,9,1,-,1,1,3.0,1,0
25,4922,Punto de Nieve Santa Inés,1,0,6,2,2,"1,8",1,1,-,-,0,1,NaN,1,1
26,12,Valdelinares,1,0,1,12,14,17,6,4,4,-,0,1,NaN,1,0
27,28,Valdezcaray,1,0,1,10,26,"22,35",6,6,10,2,1,0,2.0,0,0
28,29,La Pinilla,1,0,1,13,23,"15,57",4,6,13,-,0,0,NaN,0,0
29,26,Puerto de Navacerrada,1,0,2,6,8,"5,1",1,3,4,-,0,0,NaN,0,0
30,2379,Sierra de Béjar,1,0,6,4,19,"17,66",5,6,8,-,0,0,NaN,1,0
31,27,Valdesquí,1,0,2,15,28,"22,24",7,16,5,-,0,1,NaN,0,0
32,4,Sierra Nevada,1,0,1,21,131,"111,4",19,45,53,7,1,1,7.0,1,1
33,4601,Grandvalira,1,0,1,74,138,210,24,54,42,18,0,1,NaN,1,0
34,38,Ordino Arcalís,1,0,4,17,28,"30,5",9,7,10,2,0,1,NaN,1,0
35,39,Pal Arinsal,1,0,1,32,45,63,6,18,17,4,0,1,NaN,1,0
36,2824,Ski Canaro,1,0,1,2,2,"0,5",2,-,-,-,0,0,NaN,1,0
37,1533,Artouste,1,0,6,11,20,25,2,12,5,1,0,1,NaN,1,0
38,234,Gourette,1,0,1,12,37,39,7,11,16,3,0,1,NaN,1,0
39,2225,La Pierre Saint-Martin,1,0,1,11,27,27,6,12,7,2,0,1,NaN,1,0

In [19]:
df.dtypes

id                      int64
name                   object
downhill_skiing         int64
nordic_skiing           int64
status_id               int64
lifts_total             int64
runs_total              int64
km_total               object
green_runs_total        int64
blue_runs_total        object
red_runs_total         object
black_runs_total       object
special_runs            int64
snowpark                int64
special_runs_total    float64
trineos                 int32
esqui_de_fondo          int32
dtype: object

In [25]:
df.special_runs_total.fillna(0,inplace=True)

In [67]:
df.special_runs_total = df.special_runs_total.astype(int)

In [51]:
df.km_total = df.km_total.str.replace(',','.')

df.km_total = df.km_total.astype(float)

AttributeError: Can only use .str accessor with string values!

In [59]:
df.runs_total = df.runs_total.astype(int)

In [71]:
df.black_runs_total.replace('-', '0', inplace=True)

In [72]:
df.red_runs_total.replace('-', '0', inplace=True)

df.blue_runs_total.replace('-', '0', inplace=True)

In [73]:
df.blue_runs_total = df.blue_runs_total.astype(int)

df.red_runs_total = df.red_runs_total.astype(int)

df.black_runs_total = df.black_runs_total.astype(int)

In [74]:
df.head(18)

,id,name,downhill_skiing,nordic_skiing,status_id,lifts_total,runs_total,km_total,green_runs_total,blue_runs_total,red_runs_total,black_runs_total,special_runs,snowpark,special_runs_total,trineos,esqui_de_fondo
0,22001,Alp 2500,1,0,1,33,145,145.0,29,49,44,16,0,0,0,0,0
1,20,La Molina,1,0,1,16,71,71.0,20,18,22,6,0,1,0,1,0
2,19,Masella,1,0,1,17,74,74.0,9,31,22,10,0,0,0,0,0
3,16,Baqueira Beret,1,0,1,36,170,170.0,5,43,48,17,1,1,3,0,1
4,17,Boí Taüll,1,0,1,10,46,46.0,6,6,15,16,0,1,0,1,0
5,18,Espot,1,0,1,5,25,25.0,2,10,6,4,0,0,0,1,0
6,21,Port Ainé,1,0,1,7,27,27.0,6,4,11,4,0,1,0,1,0
7,22,Port del Comte,1,0,1,17,50,50.0,8,13,12,6,0,0,0,0,0
8,2412,Tavascán,1,0,4,3,7,7.0,2,1,2,2,0,0,0,0,0
9,23,Vall de Nuria,1,0,1,7,8,8.0,3,3,3,2,0,0,0,1,0
10,24,Vallter,1,0,4,10,13,13.0,3,4,6,0,0,0,0,1,0
11,22003,100K Astún - Candanchú,1,0,1,37,100,100.5,17,32,40,19,1,0,10,0,0
12,7,Astún,1,0,1,15,50,50.0,5,18,22,6,1,1,10,1,0
13,8,Candanchú,1,0,1,22,50,50.5,12,14,18,13,0,0,0,1,0
14,9,Cerler,1,0,4,20,80,80.0,10,19,27,16,1,1,1,0,0
15,22002,Formigal - Panticosa,1,0,1,37,182,182.0,12,36,52,42,1,0,5,0,0
16,10,Formigal,1,0,1,22,143,143.0,6,20,35,37,1,1,4,0,0
17,11,Panticosa,1,0,1,15,39,39.0,6,16,17,5,1,0,1,0,0

In [76]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 68 entries, 0 to 67
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  68 non-null     int64
 1   name                68 non-null     object
 2   downhill_skiing     68 non-null     int64
 3   nordic_skiing       68 non-null     int64
 4   status_id           68 non-null     int64
 5   lifts_total         68 non-null     int64
 6   runs_total          68 non-null     int32
 7   km_total            68 non-null     float64
 8   green_runs_total    68 non-null     int64
 9   blue_runs_total     68 non-null     int32
 10  red_runs_total      68 non-null     int32
 11  black_runs_total    68 non-null     int32
 12  special_runs        68 non-null     int64
 13  snowpark            68 non-null     int64
 14  special_runs_total  68 non-null     int32
 15  trineos             68 non-null     int32
 16  esqui_de_fondo      68 non-null     int32
dtypes: float64(1), int32(7), int64(8), object(1)
memory usage: 7.3+ KB